// ═══════════════════════════════════════════════════════════
// WAT IS ER NIEUW: ÉÉN REGEL PER WIJZIGING, NOOIT EEN REGEL HERSCHRIJVEN
// ═══════════════════════════════════════════════════════════
// Hier stond ooit één zin, `LAATST_BIJGEWERKT`, waar elke chat zijn nieuws
// vóórin plakte. Die zin groeide naar vijfduizend tekens op één regel, en
// iedere chat die iets opleverde herschreef precies díe regel. Twee chats op
// dezelfde dag botsten dus gegarandeerd, en op 11 augustus 2026 zijn de
// conflictmarkeringen twee keer meegecommit. Gevolg: de bouw mislukte, de site
// bleef twee opleveringen lang op oude code staan, en niemand zag het.
//
// Daarom nu twee afspraken die samen het botsen onmogelijk maken:
//
//  1. ÉÉN WIJZIGING IS ÉÉN REGEL, EN JE VOEGT HEM BOVENAAN TOE. Je past nooit
//     een bestaande regel aan. Twee chats die allebei iets toevoegen maken dan
//     twee losse regels, geen twee versies van dezelfde regel.
//  2. `.gitattributes` ZET DIT BESTAND OP `merge=union`. Botsen twee chats
//     toch op dezelfde plek, dan houdt git ze allebei in plaats van er een
//     conflict van te maken. Er kunnen hier dus nooit conflictmarkeringen in
//     belanden, en dat is precies wat de bouw sloopte.
//
// Voorwaarde voor punt 2: elke regel moet op zichzelf kloppen. Vandaar de
// vaste, eenregelige vorm hieronder. Verdeel een lange tekst nooit over
// meerdere regels; dan kan een union-merge er wél iets kapots van maken.
// `proeven/wat-is-nieuw.proef.ts` bewaakt die vorm bij elke bouw.
// ═══════════════════════════════════════════════════════════

export type Nieuwtje = { datum: string; tekst: string };

/** Nieuwste bovenaan. Datum als JJJJ-MM-DD, tekst in gewone taal, één regel. */
export const WAT_IS_NIEUW: Nieuwtje[] = [
  { datum: "2026-08-14", tekst: "De interne documentweergave (waar een link naartoe wijst als een stap ooit zonder gekozen Drive-map is gemaakt) heeft nu de knop \"Kies Drive-map en upload\": hij zet de al vastgelegde tekst om naar het Pingwin-document in de gekozen map, zonder de tekst opnieuw te laten schrijven. Vanaf dat moment gebruiken Developer en Mail die nieuwe Drive-link vanzelf, in plaats van dat je de hele stap opnieuw moet starten." },
  { datum: "2026-08-14", tekst: "Het openen van een projectkaart met een gevuld maildossier gaf een zichtbare flits: \"Waarom deze pagina\" en \"Aanpak en afspraken\" verschenen even en werden dan meteen weer weggehaald zodra bleek dat het levende dossier hetzelfde verhaal actueler vertelde. Die twee blokken tonen zich nu pas zodra vaststaat dat ze nodig zijn, dus nooit meer aan en meteen weer uit." },
  { datum: "2026-08-14", tekst: "Een Drive-map kiezen is nu verplicht vóór elk document, in plaats van een vrijblijvende suggestie. Start je op de projectkaart een fase die een document maakt (strategie vastleggen, analyse, blauwdruk, copy, \"Alles in één keer\") zonder gekozen map, dan klapt de mapkiezer vanzelf open en draait de actie pas zodra je kiest of een nieuwe map maakt. Hetzelfde geldt nu op de Pagina's-pagina voor \"Vat samen & leg strategie vast\", \"Document opnieuw maken\", en het overnemen van interne links, structured data en cannibalisatie-aanbevelingen. Zo landen alle documenten van een pagina, in elke fase, gegarandeerd in dezelfde klantmap in Drive, in plaats van dat een deel daar terechtkomt en een ander deel alleen in het dashboard blijft hangen." },
  { datum: "2026-08-14", tekst: "Vervolgreparatie: het copy-document ontbrak nog steeds in het mail- en doorzetvenster als de copy ooit zónder gekozen Drive-map was gemaakt (er lag dan geen Drive-link, dus was er niets om aan te vinken, ook al bestond de tekst wel). Ontbreekt die Drive-link, dan wijst het venster nu naar de interne documentweergave (met daarin de knop om alsnog een Word-bestand te downloaden), voor copy, blauwdruk én analyse. Zo staat er altijd iets om mee te sturen zodra een stap gegenereerd is." },
  { datum: "2026-08-14", tekst: "Drie reparaties rond het doorzetten naar de developer. Eén: het copy-document werd wel getoond in het doorzet-venster en het mailvenster, maar stond niet standaard aangevinkt, waardoor een taak of mail er soms zonder de copy uitging; hij staat nu standaard aan (naast de pagina en een eventuele goedgekeurde klantversie). Twee: bij een pagina met meerdere losse klantversies kon de copy zelfs helemaal buiten de lijst vallen door de grens van zes documenten; copy, blauwdruk en analyse staan nu vooraan in de lijst en vallen dus nooit meer weg. Drie: de \"Gedaan\"-meting (en \"Is dit doorgevoerd?\") toont nu een klikbare link naar het document waarmee vergeleken is, zodat duidelijk is welke copy-versie de bron was." },
  { datum: "2026-08-14", tekst: "De Implementatie-rij op een projectkaart heeft nu ook \"Developer\" (hetzelfde doorzet-venster als onderaan de kaart, met de Drive-documenten erbij) en \"Gedaan\" (her-fetcht de live pagina en meet of de wijziging er echt staat; klopt het, dan vinkt Implementatie zichzelf af en kun je door naar Structured data), naast de bestaande Mail-knop. En start je een analyse, blauwdruk of copy zonder dat er een Drive-map gekozen is, dan knippert de knop \"Drive-map kiezen of maken\" nu even en klapt de mapkiezer meteen open, zodat het geen document meer wordt dat stilletjes zonder klantmap blijft staan." },
  { datum: "2026-08-14", tekst: "Het aparte vak \"Opdrachten in deze kaart\" op een projectkaart is weg: de herkomst van zo'n regel (chat, mail, scan, of eigen tekst) was er niet aan af te zien, dus ook niet te vertrouwen als los, afvinkbaar lijstje. De tekst zelf is niet weg; die staat nu gewoon onder \"Aanpak en afspraken\", net als de rest van de kaart." },
  { datum: "2026-08-14", tekst: "Advies dat je met \"Gelieerde pagina's\" naar andere pagina's doorgeeft, wordt nu automatisch overal ingetrokken zodra je de strategie van de bronpagina opnieuw vastlegt; oud advies kan de nieuwe strategie dan niet meer tegenspreken. Op de ontvangende pagina zie je dat meegegeven advies nu ook met een knop \"Negeer dit advies\" als het achterhaald is, en de chat weegt jouw eigen, actuele tekst voortaan altijd zwaarder dan zo'n ouder advies." },
  { datum: "2026-08-14", tekst: "Het Developer-tabblad is opgeruimd: de pagina staat weer binnen de normale schermbreedte in plaats van beeldvullend, de kolom \"Opm. developer\" en de knop \"Kaart\" (voor de developer niet relevant) zijn weg uit de lijst per klant, en een taak met een lange titel blijft nu één regel hoog met puntjes erachter in plaats van de hele rij op te rekken." },
  { datum: "2026-08-14", tekst: "In het Developer-tabblad kun je nu bij een taak die van een projectkaart komt met één klik \"Is dit doorgevoerd?\" checken, zonder eerst de kaart in de weekplanning op te hoeven zoeken. En in elk mailvenster in het dashboard (zoals \"Mail over deze taak\") kun je nu een screenshot plakken of erin slepen; hij gaat als afbeelding onderaan de mail mee." },
  { datum: "2026-08-14", tekst: "\"Wat we doen\" is compleet gemaakt: een taak die je op Klaar/Verwerkt zet komt er nu vanzelf in, net als een verstuurde mail met echt werk erin (met klikbare link naar de mail, standaard alleen voor jou zichtbaar totdat je 'm deelt) en een gedetecteerde sitewijziging (nu met de echte oude en nieuwe tekst in plaats van \"pagina aangepast\"). Bestaande regels zoals een redirect tonen voortaan het echte van-adres en naar-adres in plaats van een vaste zin. Heeft een dag meer dan vijf regels van hetzelfde type (bijvoorbeeld tientallen redirects), dan vouwt die groep zich automatisch samen tot één regel die je open kunt klikken." },
  { datum: "2026-08-13", tekst: "\"Mail erbij zoeken\" op een kaart doorzocht alleen de laatste vijftien mails van de klant, in willekeurige volgorde qua onderwerp; de mail die echt bij de pagina hoorde stond er daardoor vaak niet eens bij. Hij zoekt nu ook gericht op de kernwoorden van de pagina, net als de automatische koppeling, sorteert op relevantie, en laat automatische meldingen (Ahrefs, Search Console e.d.) helemaal weg; dat is geen correspondentie over een pagina." },
  { datum: "2026-08-13", tekst: "Twee reparaties aan de mailkoppeling per pagina, naar aanleiding van een kaart die een mail over iets heel anders (een concurrerende kliniek) als \"bewijs\" liet zien. Eén: de AI-controle die per mail beoordeelt of hij echt bij de pagina hoort, gaf de mails eerder lange, op elkaar lijkende mail-kenmerken mee; bij een lange lijst kon het model daardoor het oordeel van de ene mail aan een andere vastplakken. Nu krijgt elke mail een simpel volgnummer, dat is voor een taalmodel veel lastiger te verwisselen. Twee: \"Mail erbij zoeken\" op een kaart toonde altijd gewoon de laatste vijftien mails van de klant, in willekeurige volgorde qua onderwerp; die lijst staat nu gesorteerd op wat er echt bij de open pagina past, met dezelfde puntentelling die de automatische koppeling ook gebruikt." },
  { datum: "2026-08-12", tekst: "De documentketen heeft nu een poort tegen tegenspraak: vlak voor een analyse, blauwdruk of copy gegenereerd wordt, vergelijkt het dashboard het vastgelegde plan en de eerdere stappen met de verse meting van de pagina. Botst een claim hard met een gemeten feit (het plan noemt een sectie \"ontbrekend\" die live al bestaat, of verwijst naar een pagina die niet bestaat), dan komt er geen document maar een melding die precies zegt welke claim botst met welk feit en hoe je verder kunt. Daarbij hoort de werkregel dat een strategie intern blijft totdat de analyse hem bevestigd heeft; de assistent wijst je erop als je een onbevestigde strategie naar een klant wilt sturen. Liever geen document dan twee documenten die elkaar tegenspreken." },
  { datum: "2026-08-12", tekst: "Drie adviesregels aangescherpt, geboren uit een echte klantcasus waarin de sitebouwer de pagina net zelf had bijgewerkt: (1) bij elk pagina-advies en elk document wordt de pagina op dat moment vers opgehaald, met de datum erbij (\"live gecheckt op ...\"), zodat een advies nooit meer iets kan \"missen\" dat er al op staat; (2) de commerciële laag wordt gedoseerd naar de top 10 in Google (overwegend informatieve zoekresultaten = een kort kostenblok met link, geen volledige verkoopsecties); (3) zoekersvragen worden eigen koppen in de tekst in plaats van een los FAQ-blok, want FAQ-blokjes in de zoekresultaten bestaan sinds mei 2026 niet meer en de waarde zit in het antwoord zelf." },
  { datum: "2026-08-12", tekst: "De sitemap-check kan het nu aan Google zelf vragen: het blok \"Wat ziet Googlebot?\" inspecteert een dwarsdoorsnede van pagina's via Search Console (URL-inspectie) en toont per pagina wanneer Googlebot er voor het laatst was, of het ophalen toen lukte (daar zie je een blokkade) en of de pagina in de index staat. Zo is met feiten te zeggen of een botblokkade op de site ook Google raakt, of alleen meettools." },
  { datum: "2026-08-12", tekst: "Per klant is er nu een sitemap-check (link bij Zoekwoorden & links en bij de paginalijst). Die haalt de sitemap van de site vers op en beantwoordt drie vragen met feiten in plaats van vermoedens: is de sitemap zelf bereikbaar en verwijst robots.txt ernaar, welke live pagina's staan er niet in (met hun vertoningen, belangrijkste bovenaan), en welke regels erin wijzen naar een pagina die al is omgeleid of weg is. Aanleiding: bij One Day Clinic bleek de sitemap niet bij te houden wat er echt live staat, en blokkeerde de site bovendien geautomatiseerde lezers van het bestand. De uitkomst is meteen de werklijst voor de sitebeheerder." },
  { datum: "2026-08-12", tekst: "De paginalijst mist geen live pagina's meer, en besluiten uit een chat landen voortaan op de werklijst. Bij het inlezen van een website worden nu vier bronnen verenigd (sitemap, Search Console, Ahrefs en de interne links op de pagina's zelf) in plaats van alleen de sitemap; een live pagina die niet in de sitemap staat krijgt het label \"niet in sitemap\", want dat is zelf een bevinding. Aanleiding: een pagina van One Day Clinic die op ruim twintig zoektermen rankte was voor het dashboard onzichtbaar. Daarnaast kunnen cluster-besluiten uit een chat (zoals de vijf besluiten over het cluster \"soa test amsterdam\") nu rechtstreeks in de werklijst worden opgenomen, met label \"besluit uit chat\" en de volledige onderbouwing; ze overrulen de motor-uitkomst, net als een handmatige correctie. En zodra de laatste samenvoeging naar een doelpagina is doorgevoerd, zet het dashboard automatisch één optimalisatietaak voor die pagina op de weekplanning: eerst alles erin, dan pas optimaliseren, zonder dat iemand dat moment hoeft te bewaken." },
  { datum: "2026-08-12", tekst: "De samenvoegingen in de werklijst hebben nu hun eigen doorvoerknop, en die dwingt de goede volgorde af: eerst de content, dan pas de redirect. Eén klik op \"Wat moet er over?\" vergelijkt de pagina met zijn doel en zegt precies wat het doel nog mist: welke secties, welke zoekopdrachten waarop de oude pagina wordt gevonden, en welke interne links nog naar het oude adres wijzen. Daar rolt een kant-en-klare, genummerde instructie voor de sitebouwer uit, die met \"Naar planning\" op de taakkaart meegaat en los te kopiëren is. De redirect-knop gaat pas open nadat \"content staat over\" is aangevinkt, en die poort zit ook aan de serverkant. Is er niets over te zetten (geen eigen secties, geen zoektermen die het doel niet dekt), dan zegt het briefje dat zelf en kan de redirect meteen. Een pagina die niet gelezen kon worden geeft nooit \"meteen\": bij een meetfout blijft de poort dicht." },
  { datum: "2026-08-12", tekst: "Het chatscherm van de paginakaart (de zes stappen bij een pagina: strategie, doorgeven, documenten, cannibalisatie, interne links en structured data) stond als één bestand van 1.662 regels in de code, het laatste en lastigste te grote bestand. Elke werksessie die iets aan één stap deed moest in dat ene bestand schrijven, dus twee sessies op één dag botsten altijd. Het is nu een bestand per stap, met een karkas dat alleen nog vasthoudt wat stappen samen gebruiken (de Drive-map, de foutregel, de klaar-standen); het grootste stuk is 398 regels. Op het scherm verandert er niets: oud en nieuw zijn met dezelfde gegevens en dezelfde kliks naast elkaar gezet en tekenen letter voor letter dezelfde HTML, in drie situaties (vol scherm, leeg scherm, analyses die draaien). Daarmee is de erfenis-lijst van de 1.000-regels-poort weer een bestand korter." },
  { datum: "2026-08-11", tekst: "De werklijst van het opruimen laat nu zien hoever je bent. De kaarten telden alleen werk (\"38 opruimen\" bleef 38, ook als de eerste omleidingen al live stonden); onder opruimen en samenvoegen staat nu hoeveel er al op de site staan en hoeveel er nog te gaan zijn, met bij de regel zelf een label \"staat op de site\". Dat komt uit dezelfde vastgelegde besluiten waarin de doorvoerknop zijn vinkje zet, dus een redirect die je eerder of via de oude tabel plaatste telt gewoon mee, en \"Voer alles door\" slaat die regels voortaan over in plaats van ze nog een keer te plaatsen. Verder zijn de groepen in de lijst uitklappers geworden die standaard dicht staan: die ene groep van 38 duwde de andere vier besluiten van het scherm af, en dicht zie je in vijf regels waar het werk zit. Filter je op één besluit, dan staat die groep wel open." },
  { datum: "2026-08-11", tekst: "De projectkaart in de weekplanning stond als één bestand van 1.206 regels in de code: de kop, de fases, het gesprek, het dossier, de bespreeklijst en de werklijst door elkaar heen. Elke werksessie die iets aan de kaart deed moest daar in schrijven, dus twee sessies op één dag botsten altijd, ook als de een aan de chat werkte en de ander aan de fases. Het is nu een bestand per onderdeel, met een karkas van 150 regels dat ze alleen nog in de goede volgorde zet; het grootste stuk is 339 regels. Op het scherm verandert er niets, dat is regel voor regel nagelopen. Er is meteen een poort bijgekomen die de bouw tegenhoudt zodra een bestand weer boven de 1.000 regels uitkomt, met de vier bekende dikkerds op een lijst die alleen korter mag worden." },
  { datum: "2026-08-11", tekst: "De uitleg die je nu leest stond als één bestand van 2.629 regels in de code, en elke werksessie die iets opleverde moest daar in schrijven. Twee sessies op één dag botsten dus altijd, in tekst die niets met elkaar te maken had. Het is nu één bestand per hoofdstuk, en de twee grootste hoofdstukken (de motoren en de eerlijke agenda) hebben een eigen map met een bestand per onderwerp: acht motoren apart, en de drie golven van de routekaart apart. Aan de tekst zelf is geen letter veranderd, dat is nagerekend. Een poort bewaakt dat geen enkel stuk terug boven de 250 regels groeit en dat er nooit een hoofdstuk losraakt van de pagina." },
  { datum: "2026-08-11", tekst: "Haalt een paginatitel of omschrijving onze eigen lat niet, dan zegt de oplevering er nu bij waaróm, en of het aan de tekst ligt of aan het opgegeven zoekwoord. Dat laatste bleek bij een echte pagina het geval: het primaire zoekwoord stond er als een zin van vijf woorden, en zoiets kan per definitie niet vooraan in een titel van zestig tekens staan en niet letterlijk in een leesbare omschrijving. Drie criteria zakken dan zonder dat er iets mis is met het schrijfwerk." },
  { datum: "2026-08-11", tekst: "In een copy-briefing stonden de vier stappenblokken zonder titel en zonder nummer in beeld, met een kader dat onderaan te veel lucht overhield. Het bolletje en de titel zaten in een tabelletje bínnen het kader, en niet elke lezer tekent zoiets; de hoogte rekende wél met die titelregel, vandaar de ruimte. De titel staat nu boven het kader, precies zoals een hoofdstuktitel is opgebouwd, en het kader bevat alleen nog de tekst en sluit daar strak omheen. Er staat ook wat vet in, zodat het geen egale blokken meer zijn." },
  { datum: "2026-08-11", tekst: "Bij de paginatitel en de omschrijving staat in het klantdocument nu de verificatie: elk criterium waaraan getoetst is, met de gemeten waarde erachter. Dat is exact dezelfde criterialijst als het meta-paneel in het dashboard gebruikt, inclusief de pixelbreedte, dus het document kan niet iets anders beweren dan het scherm. De lijst verschijnt alleen als álles klopt, want een kruisje in een oplevering is een oordeel over eigen werk." },
  { datum: "2026-08-11", tekst: "Uitgezocht waarom de paginatitel en de omschrijving niet altijd aan de criteria voldeden: we gaven het model een regel in tekens en rekenden het af in pixels, en die twee liepen niet gelijk. Een omschrijving van 129 tekens haalde onze eigen tekenregel en bleef twintig pixels onder het venster van Google. De pixel is nu de enige norm en het tekenbereik wordt daaruit afgeleid, aan de tekst zelf gemeten. Daarbovenop hoort het model hoevéél het scheelt in plaats van alleen dat het mis is, levert het drie varianten per ronde in plaats van één, en is er een laatste slag op puur rekenwerk die inkort op een natuurlijke grens of aanvult met eigen woorden van de klant, en die niets doet als het resultaat niet echt klopt. Haalt een tekst het dan nog niet, dan meldt de oplevering dat in plaats van te zwijgen." },
  { datum: "2026-08-11", tekst: "De copy-briefing zei alles twee keer: het opgeslagen copydocument is zelf al een briefing, en het klantdocument bouwt diezelfde hoofdstukken vers op uit de actuele cijfers. Uit dat opgeslagen document komen nu alleen nog de webteksten, waardoor ook de aanduidingen H1, H2 en H3 weer alleen bij tekst staan die echt op de site komt. Verder rekenen de kaders hun hoogte uit door de tekst af te breken zoals hij op papier afbreekt, dus de openingstekst loopt niet meer onder zijn kader uit, en de 404-controle op het omslagbeeld kijkt ook naar het begin van de zichtbare tekst." },
  { datum: "2026-08-11", tekst: "Klik je op een copy- of analyselink van een pagina zonder Drive-bestand, dan kreeg je ruwe tekst in plaats van het opgemaakte stuk. Er is nu een knop die het document in de huisstijl opbouwt uit wat er al ligt, met of zonder Drive-map; bij copy is dat de volledige klant-briefing met omslag, uitleg, zoekwoorden en webteksten." },
  { datum: "2026-08-11", tekst: "Elke pagina die opgeruimd wordt krijgt nu ook een voorgestelde bestemming, met twee knoppen ernaast: de redirect plaatsen en de redirect testen. De bestemming volgt een vaste ladder (de inhoudelijke opvolger, anders de dichtstbijzijnde zusterpagina, anders de categorie erboven, anders een 410, en alleen bij externe links de homepage), en bij een plaatspagina is dichtstbijzijnde letterlijk te nemen: de ligging wordt opgezocht bij de plaatsendienst van de overheid en de bestemming is de vestiging die het dichtst bij ligt, waarbij alleen plaatsen tellen waar de klant echt zit. Dat maakt uit: bij One Day Clinic haalt het locatie-overzicht nul bezoekers terwijl de vijf stadspagina's er samen ruim vijftienhonderd per maand halen, dus alles naar dat overzicht sturen voedde precies de zwakste pagina. Boven veertig kilometer is een andere stad geen vervanging meer en gaat de pagina alsnog naar het overzicht. Testen vertelt wat een bezoeker echt krijgt: welke status, hoeveel tussenstappen, waar je uitkomt, of dat eindpunt bestaat en indexeerbaar is, en of er een cache voor de site zit die de oude pagina nog toont." },
  { datum: "2026-08-11", tekst: "De mailknop bij een taak in de developerlijst deed niets meer, terwijl er niets aan die knop veranderd was: hij sprong naar je eigen mailprogramma, en dat werkt alleen zolang er in die browser een mailprogramma aan mailadressen hangt. Valt dat weg, dan gebeurt er letterlijk niets, geen venster en geen melding, dus lijkt de knop stuk. Nu opent hetzelfde mailvenster als overal elders in het dashboard, met de klant, de taak, de pagina en de documenten er al in, en verstuurt hij via de mailkoppeling; het adres erboven is aan te passen en wordt onthouden, want de een mailt zijn sitebouwer en de ander mailt juist terug. Dezelfde constructie stond op drie plekken los in de code, dus dezelfde storing lag drie keer klaar; die lopen nu over één stukje code, en een proef bij elke bouw houdt tegen dat er een nieuwe mailknop bijkomt die stilzwijgend niets kan doen." },
  { datum: "2026-08-11", tekst: "Een vraag in de chat van een projectkaart kon zonder antwoord én zonder melding blijven hangen: de reden werd wel bepaald, maar getekend in de fase-lijst, en een kaart zonder pagina heeft die lijst niet. Je zag dus niets, stelde de vraag opnieuw, en had twee identieke vragen zonder antwoord in beeld. Nu staat de melding onder de vraag zelf, komt je vraag terug in het invulveld zodat overtypen of plakken niet meer nodig is, en zit er een knop 'Probeer opnieuw' naast. Daarnaast kapt het dashboard een te zware vraag nu zelf af, net vóór de tijdslimiet van de server, met een leesbare uitleg in plaats van een leeg scherm, en beginnen de extra denkrondes (afronden, uitschrijven, feitencontrole) alleen nog als er ook echt tijd voor is, zodat een compleet antwoord niet meer verloren gaat aan een ronde die er niet meer bij paste." },
  { datum: "2026-08-11", tekst: "Het nieuws op deze pagina stond als één zin van vijfduizend tekens op één regel, en elke chat die iets opleverde herschreef precies die regel; twee chats op dezelfde dag botsten dus altijd, en vandaag zijn de conflictmarkeringen twee keer meegecommit, waardoor de bouw mislukte en de site twee opleveringen lang op oude code bleef staan zonder dat iemand het zag. Nu is één oplevering één regel die je erbij zet in plaats van een regel die je herschrijft, houdt git bij een botsing beide regels in plaats van er een conflict van te maken, en mislukt de bouw met een leesbare melding zodra er ergens toch een half samengevoegd bestand in de code staat. Zichtbaar gevolg: de kopbalk toont weer gewoon een datum, en het nieuws staat in een eigen uitklapper met een regel per oplevering." },
  { datum: "2026-08-11", tekst: "Elke pagina die opgeruimd wordt krijgt nu ook een voorgestelde bestemming, gekozen langs een vaste keuzeladder: de inhoudelijke opvolger, anders de dichtstbijzijnde zuster, anders de categorie erboven, anders 410, en alleen bij externe links de homepage. Bij het voorstel staat welke trede het werd, waarom de hogere treden afvielen, en hoe zwaar de keuze weegt (externe links en resterend verkeer). Ernaast twee knoppen: de redirect plaatsen (die meet zichzelf daarna na) en de redirect testen (status, aantal tussenstappen, eindpunt, en of dat eindpunt 200 geeft en indexeerbaar is). Bij plaatspagina's wordt de zusterstad bewust overgeslagen en 410 is een volwaardige uitkomst in plaats van een fout." },
  { datum: "2026-08-11", tekst: "Een documentlink opent nu meteen in Google Docs in bewerkmodus in plaats van in het kijkscherm van Drive, ook bij documenten die er al maanden staan; een pdf of afbeelding houdt zijn gewone Drive-link. En een kop staat nooit meer alleen onderaan een bladzijde met zijn tekst op de volgende: koppen, tabelkopregels en de witregel eronder schuiven mee. Dat zit in de bouwstenen, dus het geldt voor elk Pingwin-document, en een proef controleert het bij elke bouw in het echte Word-bestand." },
  { datum: "2026-08-11", tekst: "Uitgezocht waarom de paginatitel en de omschrijving niet altijd aan de criteria voldeden: we gaven het model een regel in tekens en rekenden het af in pixels, en die twee liepen niet gelijk. Een omschrijving van 129 tekens haalde onze eigen tekenregel en bleef 20 pixels onder het venster van Google. De pixel is nu de enige norm, het tekenbereik wordt daaruit afgeleid en aan de tekst zelf gemeten. Daarbovenop: het model hoort hoeveel het scheelt in plaats van alleen dat het mis is, het levert drie varianten per ronde in plaats van een, en er is een vijl die met puur rekenwerk inkort op een natuurlijke grens of aanvult met eigen woorden van de klant, en die niets doet als het resultaat niet echt klopt. Haalt een tekst het dan nog niet, dan meldt het dashboard dat bij de oplevering in plaats van te zwijgen." },
  { datum: "2026-08-11", tekst: "Klik je op een copy- of analyselink zonder Drive-bestand, dan krijg je nu het opgemaakte Word-document in de huisstijl in plaats van ruwe tekst." },
  { datum: "2026-08-11", tekst: "De copy-briefing voor de klant is opgeschoond: de uitleg stond er twee keer in (een keer vers opgebouwd, een keer uit het opgeslagen copy-document) en de paginatitel en omschrijving ook; nu wordt uit dat opgeslagen document alleen het deel overgenomen dat er nog niet staat, de webteksten. De niveau-aanduidingen H1/H2/H3 staan daardoor weer alleen bij tekst die echt op de site komt, niet boven de hoofdstukken van de briefing. Het blok met de paginatitel en de omschrijving heeft geen oordeelkolom meer: alleen de opgeleverde tekst plus de meting. De kaders in een document berekenen hun hoogte nu door de tekst echt af te breken zoals hij op het scherm afbreekt, dus de openingstekst loopt niet meer onder zijn kader uit. Een hoofdstuktitel krijgt lucht boven zich en blijft aan zijn eerste alinea vastgeplakt, dus hij blijft niet meer als losse regel onderaan een pagina achter. En de 404-controle op het omslagbeeld kijkt ook naar het begin van de zichtbare tekst, want niet elk thema zet \"404\" in een echte kop." },
  { datum: "2026-08-11", tekst: "De Drive-map van een pagina kies of maak je nu bovenaan de fases, waar de documenten ook gemaakt worden. Bestaat die map nog niet (bij een nieuwe pagina is dat de regel), dan maak je hem in hetzelfde venster, met een voorgestelde naam uit het pad van de pagina, en sta je er meteen in zodat hij ook echt vastgelegd wordt; eerder werd de map wel gemaakt maar niet gekozen, en landden de documenten een niveau hoger. Het vinkje “geldt” bij een document verschijnt alleen nog als er meer dan één versie van dat soort ligt; is er maar één, dan geldt die vanzelf, ook op de kaarten die er al stonden. De standaardzinnetjes per fase (“tekst aanscherpen”, “toets deze pagina op overlap”) zijn uit beeld: die herhaalden alleen de naam van de fase en bleven staan als de fase allang af was. En het archief onderaan de kaart heet nu “Oude versies van deze kaart” met de waarschuwing erbij dat het niet actueel is." },
  { datum: "2026-08-11", tekst: "Documentlinks openen overal in een nieuw tabblad in plaats van een los venster; documenten staan overal in proces-volgorde (analyse, blauwdruk, copy) in plaats van nieuwste eerst; en een gegenereerde tekst zonder Drive-bestand heeft nu altijd een link, naar de interne documentweergave." },
  { datum: "2026-08-11", tekst: "De cockpit opent een stuk sneller, doordat de app niet meer bij elke koude server honderd keer controleert of de database klopt, elk tabblad pas gedownload wordt als je het opent, en de planning haar gegevens meteen ophaalt in plaats van te wachten tot alle code binnen is." },
  { datum: "2026-08-11", tekst: "De controle “Is dit doorgevoerd?” zoekt het copydocument op alle plekken waar het kan liggen, inclusief het gekoppelde document in Drive." },
  { datum: "2026-08-11", tekst: "In de kaart-chat staan de knoppen “Mail deze analyse” en “Vat samen & leg strategie vast” direct onder het antwoord; de dossierkaartjes van pagina's die in het antwoord genoemd worden staan erónder en standaard ingeklapt. Het samenvatten leest bovendien het hele gesprek ruim terug, dus ook een lange analyse gaat volledig mee." },
  { datum: "2026-08-11", tekst: "Aantekeningen bij een taak bewaren zichzelf, ook als je de taak meteen dichtklapt of wegklikt; een opengeklapte taak wordt zichtbaar uit de lijst gelicht; een nieuwe taak is nog één regel typen, waarbij de pagina uit je eigen zin gelezen wordt." },
  { datum: "2026-08-11", tekst: "De strategie vastleggen kan ook rechtstreeks op de projectkaart in de planning; de verwarrende losse knop “Strategie vastleggen” is vervangen door een eerlijk benoemde herkansing “Document opnieuw maken”; de vrije tekstvelden houden een geschiedenis bij en zijn met één klik terug te zetten via Veld terugzetten; en “Hele site opnieuw scannen” meet nu ook echt de inhoud van elke pagina, waarbij de wekelijkse scan begint bij de klant die het langst niet aan de beurt is geweest." },
  { datum: "2026-08-11", tekst: "De koppencontrole vergeleek de hoofdstukken van ons eigen copydocument met de pagina en meldde daardoor \"0 van de 5 koppen gevonden\" terwijl de teksten er gewoon op stonden; hij vergelijkt nu de echte webteksten, kiest het document dat die teksten bevat, en laat in een uitklapper zien welke koppen hij zocht en welke hij vond." },
];

const MAAND = ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"];

/** "11 augustus 2026". Leeg als de datum niet klopt. */
export function leesbareDatum(iso: string): string {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec((iso || "").trim());
  if (!m) return "";
  return `${Number(m[3])} ${MAAND[Number(m[2]) - 1]} ${m[1]}`;
}

/** Nieuwste eerst. Een union-merge kan de volgorde door elkaar gooien; dit zet hem recht. */
export function nieuwtjes(): Nieuwtje[] {
  return [...WAT_IS_NIEUW].filter((n) => leesbareDatum(n.datum)).sort((a, b) => (a.datum < b.datum ? 1 : a.datum > b.datum ? -1 : 0));
}
